### ISSUE TITLE
HA Intergration not sending MQTT

### ISSUE THREAD

**Issue by saaerkk** [ThermIQ/thermiq_mqtt-ha#38]
## Version of the custom_component
HACS 1.28.3
ThermIQ MQTT v1.3.5
## Configuration

thermiq_mqtt:
  mqtt_node: ThermIQ/ThermIQ-room2
  language: 'en'   # Change friendly names of values. Implemented languages: en,se,fi,no,de
  thermiq_dbg: False

## Describe the bug
After updating to HA 2022.11 I am not able to change variables via the HA intergration (example change Indoor temperature target -> 21C). The intergration does not send a MQTT message when I change the value in Lovelace
The intergration does read the MQTT messages it gets from the ThermIQ-room2 and also via a HA automation to read in the indoor temperature sensor values also Node-Red messages are read by the intergration.
I have checked that I am able to send messages via the HA MQTT broker and HA automations can send MQTT messages.
I have been able to changes the variables before so the installation of ThermIQ MQTT intergration has been working.
![ThermIQ_MQTT](https://user-images.githubusercontent.com/113055615/199973073-0f08347b-0646-486c-9ef0-1b43bacaec4c.jpg)
Picture from MQTT Explorer, with data from the pump and 2 write one from Node-Red and the other from ThermIQ2 web

**Comment by Dauzzen** [comment]
I have the same issue. Home Assistant 2022.11.1.

**Comment by ThermIQ** [comment]
I will look into this the comming week together with the update for EVU function

**Comment by DreamT80** [comment]
I have the same issue as well.

**Comment by Dauzzen** [comment]
![75A8F4B5-94CC-4EA8-B00E-9170AB100190](https://user-images.githubusercontent.com/98492697/200250453-b94f5398-1650-4bea-afa0-57f71a55be28.jpeg)

**Comment by ThermIQ** [comment]
This is most likely due to some other input_select/input_number not being properly/fully configured. See this post in [HA forum](https://community.home-assistant.io/t/thermiq-integration-to-control-thermia-and-danfoss-heatpumps/199262/62?u=thermiq)

**Comment by DreamT80** [comment]
Unfortunately I still have problems. Have updated to v1.3.9 / core 2022.11.2 (in that order), and also uninstalled/reinstalled it from scratch. I see this in the logs:



`2022-11-08 22:26:30.674 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/thermiq_mqtt/__init__.py", line 177, in handle_home_assistant_started_event
await create_entities_and_automations(hass)
File "/config/custom_components/thermiq_mqtt/helper.py", line 293, in create_entities_and_automations
await create_automations(hass)
File "/config/custom_components/thermiq_mqtt/helper.py", line 308, in create_automations
await add_automation(hass, OrderedDict(data), platform)
File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 838, in _async_process_config
automation_matches, config_matches = find_matches(automations, automation_configs)
File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 826, in find_matches
if automation_matches_config(automation, config):
File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 805, in automation_matches_config
return automation.name == name and automation.raw_config == config.raw_config
AttributeError: 'str' object has no attribute 'name'`

**Comment by ThermIQ** [comment]
Do you have any other intergrations or things configured?

I have run on a fresh installed HA 2022.11.2, +MQTT, +HACS, + required lovelace plugins without seeing this making it hard to debug further.

**Comment by DreamT80** [comment]
I use several integrations. If I look at HACS i have Easee EV Charger, Blitzortung Lightning Detector, Xiaomi Cloud Map Extractor, Gardena Smart System, Node-RED Companion, Svensk Postutdelning, nordpool, and nordpool_diff. Kind of hard to know where to start...However I know that there were a Python version conflict between the Gardena and Easee a while ago, maybe this is a similar problem?


I'm not sure if I want to post my entire configuration.yaml, maybe it's enough with the TermIQ-specific config?

`thermiq_mqtt:
  mqtt_node: ThermIQ/ThermIQ-room-bb
  language: 'se'   # Change friendly names of values. Implemented languages: en,se,fi,no,de
  thermiq_dbg: False`

**Comment by barvidss** [comment]
I'm having the same issue. Out of the integrations DreamT80 mentioned nordpool is the only one we have in common.

**Comment by ThermIQ** [comment]
Maybe try to disable them all and then enable one by one to see when it failing.

I will look into another way of implementing this in thermiq to make it more robust but I need help pinpointing on integration that fails so that I can debug myself

**Comment by jessenclaus** [comment]
Hi 
I also experince the same issue after update. I have also had the nordpool - tried to remove it but it dosen't help so even that this is a common thing between the posts it seems not to be the reason.

**Comment by barvidss** [comment]
I have neither of those integrations and still experience the same issue. 
Something must have happened with the 2022.11-update.

**Comment by ThermIQ** [comment]
Then try to disable u till thermiq works. Ight be more than one other causing it

**Comment by hillholder** [comment]
Hi, same issue - have nordpool:

"2022-11-09 13:43:40.303 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration thermiq_mqtt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-09 13:43:40.305 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-09 13:43:40.306 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nordpool which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-09 13:44:04.005 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform nordpool is taking over 10 seconds.
2022-11-09 13:44:11.326 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities input_number.thermiq_mqtt_indoor_requested_t or it is/they are currently not available" ... etc

BTW - if i remember right there were something Thermiq related automation(s) in /config/automation/dashboard before updates - now it/they seems  to disappeared..

**Comment by ThermIQ** [comment]
The initial warnings can safely be ignored. It's commercial before the first mqqt message is received.

**Comment by ioT-enthusiast** [comment]
> ![75A8F4B5-94CC-4EA8-B00E-9170AB100190](https://user-images.githubusercontent.com/98492697/200250453-b94f5398-1650-4bea-afa0-57f71a55be28.jpeg)

I am havin the exact same issue (as describes in [issue 37](https://github.com/ThermIQ/thermiq_mqtt-ha/issues/37)) and reference to components/automation/__init__.py:805 The lines in the thermiq-mqtt component are slightly shiftet, perhaps due to the latest update?

Traceback (most recent call last):
  File "/config/custom_components/thermiq_mqtt/__init__.py", line 177, in handle_home_assistant_started_event
    await create_entities_and_automations(hass)
  File "/config/custom_components/thermiq_mqtt/helper.py", line 293, in create_entities_and_automations
    await create_automations(hass)
  File "/config/custom_components/thermiq_mqtt/helper.py", line 308, in create_automations
    await add_automation(hass, OrderedDict(data), platform)
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 838, in _async_process_config
    automation_matches, config_matches = find_matches(automations, automation_configs)
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 826, in find_matches
    if automation_matches_config(automation, config):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 805, in automation_matches_config
    return automation.name == name and automation.raw_config == config.raw_config
AttributeError: 'str' object has no attribute 'name'

**Comment by tgmos** [comment]
> > ![75A8F4B5-94CC-4EA8-B00E-9170AB100190](https://user-images.githubusercontent.com/98492697/200250453-b94f5398-1650-4bea-afa0-57f71a55be28.jpeg)
> 
> I am havin the exact same issue (as describes in [issue 37](https://github.com/ThermIQ/thermiq_mqtt-ha/issues/37)) and reference to components/automation/**init**.py:805 The lines in the thermiq-mqtt component are slightly shiftet, perhaps due to the latest update? I don't have the Nordpool integration installed. From HACS I only have "passive BLE monitor integration", "Deutscher Wetterdienst" and "ICS" installed.
> 
> Traceback (most recent call last): File "/config/custom_components/thermiq_mqtt/**init**.py", line 177, in handle_home_assistant_started_event await create_entities_and_automations(hass) File "/config/custom_components/thermiq_mqtt/helper.py", line 293, in create_entities_and_automations await create_automations(hass) File "/config/custom_components/thermiq_mqtt/helper.py", line 308, in create_automations await add_automation(hass, OrderedDict(data), platform) File "/usr/src/homeassistant/homeassistant/components/automation/**init**.py", line 838, in _async_process_config automation_matches, config_matches = find_matches(automations, automation_configs) File "/usr/src/homeassistant/homeassistant/components/automation/**init**.py", line 826, in find_matches if automation_matches_config(automation, config): File "/usr/src/homeassistant/homeassistant/components/automation/**init**.py", line 805, in automation_matches_config return automation.name == name and automation.raw_config == config.raw_config AttributeError: 'str' object has no attribute 'name'

Same issue here

**Comment by igalg99** [comment]
I have same issue. Glad to see it is not only me and it's more global problem
I don't have any of the integrations mentioned above. It worked fine last time I tried to change something. But it was few weeks ago. Now everything I change via the integration and the dashboard is reverted. But if I change it on the heat pump it reads it fine. Basically it acts now as "read only"

**Comment by ThermIQ** [comment]
Please revert back to 1.3.5 for a known working setup.

**Comment by ThermIQ** [comment]
I need your help with the ha 2022.11 issue as I have a fully working setup.
In order to debug it I need your help to set up a configuration that fails  so please pinpoint to one specific config that fails.

**Comment by igalg99** [comment]
> Please revert back to 1.3.5 for a known working setup.

It actually didn't work from 1.3.5
When I noticed it doesn't work, I updated to latest version since I thought it would fix it. It didn't. I honestly cannot say when it appeared since only today I have noticed it. I am on HA 2022.11.1  . I was on 1.3.5 and it didn't work and then on latest. 
Hope it helps to get to the bottom of this

**Comment by tgmos** [comment]
Reverted to 1.3.5 scrip and love_lace. Same issue, same error message. Animations works in 1.3.5.

**Comment by ThermIQ** [comment]
Then  help me figure out why it breaks for you and works for.me with plain 2022.11.2

**Comment by igalg99** [comment]
I am sorry for the silly question or claim . But are you positive it works for you ? When you change the parameter in the dashboard. Does it change in the heat pump itself? 
I honestly don't know how to recreate or trace back to a working state since it just appeared . The only changes I have done lately were updating HA. So I suspect it is related to that. I have now update to 2022.11.2 to see if it fixes it. But no. Still same issue. It changes, seems to be working but then changes back. Tried to restart already everything including the thermiq -mqtt module which connected to the heat-pump. Still works as "read only" , won't make changes in the heat pump.

**Comment by ThermIQ** [comment]
Yes, it works in both read and write.

The "connection " btw input_number (what you can get Iin the ui) and the service of sending an mqtt message is broken by some other integration not being complete in its definition of input_number or input_select

Again, if you disable all integrations except thermiq  will it work?

Give me ONE integration that makes thermiq fail so that I can debug why......

**Comment by igalg99** [comment]
Ok I will try and see if I can find out something

**Comment by DreamT80** [comment]
I haven't tried disabling the other integrations (I'm afraid it will mess upp a lot in my HA install), but instead i did a clean install of HassOS 9.3/core 2022.11.2 (a virtual machine), installed ThermIQ (v1.3.5, v1.3.9 didn't seem available right now?)  and added the integrations one after another. This didn't break the the ThermIQ installation.

Could this be an upgrade related issue, where a configuration is created in a certain way, and gets broken when doing updates? Due to changes made in the HA core? I think that maybe HA is changed regarding how to match/add automations, which maybe affects automations that were added earlier.

Maybe the problem can be recreated in the following way?
- Install HA with an older core (2022.10.5, but preferably older).
- Install ThermIQ (v1.3.5 or older). Automations gets added by the integration.
- Upgrade the HA core to 2022.11.2 (does it still work?)
- Upgrade ThermIQ to v1.3.9 (does it still work?)

**Comment by ThermIQ** [comment]
> 

Thanks, I'll try that

**Comment by tgmos** [comment]
So this i what i got so far. 
Tried to downgrade both MQTT addon and Thermiq = No luck.
Tried to downgrade HA Core without luck all the way down to -> 2022.10.0 = this version seams to work fine for me.

**Comment by ThermIQ** [comment]
@tgmos : Do you have aný other automations? The error message above comes when init:ing an automation.

I will try to run a Dev Container of 2022.10.0 and upgrade it to 2022.11.2 and see if that breaks stuff. 

The debug in a virtual machine on a pc is actually quite good even for a beginner like me

**Comment by tgmos** [comment]
I have a lot of automations and addons. So i upgraded from 22.10 to 22.11.2 and it broke. Downgraded to 22.10 and still broken. So im not sure its version related. What i did to fix the issue now was to delete the mqtt thermiq information in mqtt explorer.

**Comment by ThermIQ** [comment]
**"What i did to fix the issue now was to delete the mqtt thermiq information in mqtt explorer."**

Can you elaborate, i.e what steps where taken to brake, and fix, and what has MQTT Eplorer to do with it?

**Comment by ThermIQ** [comment]
Looking at the error message:

File "/usr/src/homeassistant/homeassistant/components/automation/init.py", line 805, in automation_matches_config return automation.name == name and automation.raw_config == config.raw_config AttributeError: 'str' object has no attribute 'name'

This is now functionality added to HA during autumn

**Comment by tgmos** [comment]
In HA, i tried to change targeted indoor temp and/or setting heatpump mode to off or auto. It looks like it works but reverts back to old state after some time. There is no mqtt write produced then changing. So after i confirmed that its not working i deleted the topics "ThermIQ -> ThermIQ-room-bb" and the announce topic in MQTT Explorer, then tried changing mode/temp again and it produces a write command, and iv confirmed it on the heatpump.

**Comment by ThermIQ** [comment]
HA:
When changing an input_number it displays it's new value trigger an automation that sends an MQTT wite message. The heatpump changes it's value and confirms back with a complete register log which is used, again with an automation, to update the input_number.

When the write automation fails (or isn't installed or ...) you get the behaviour you describe

MQTT Explorer
I don't understand how this can affect HA all

**Comment by tgmos** [comment]
You are right, disregard the above. The only thing i can say for sure is that 2022.10.5 works for me without disabling any addons or automations, but in 11.0 ThermIQ is broken for some reason.

**Comment by ThermIQ** [comment]
I have now been able to reproduce the issue:
- Clean install HA 2022.11.02, +MQTT, +HACS, +ThermIQ (inc lovelace)
This works fine

- Add an automation through the GUI, i.e "at Sunrise create event"

Restart and ThermIQ will now fail. I need to review the whole concept of "built in automations"

**Comment by Dauzzen** [comment]
Is it possible to manually adjust the value for the indoor room temperature? 
I mean - it's never possible to adjust that value directly on the heat pump manually - you have to go through the ThermIQ-module and it "sends" a value for the temperature, just as it was a real temperature sensor attached to the heat pump.
Is there a way to temporarily do this manually from HA or through MQTT Explorer for example?

**Comment by DreamT80** [comment]
> Is it possible to manually adjust the value for the indoor room temperature?
> I mean - it's never possible to adjust that value directly on the heat pump manually - you have to go through the ThermIQ-module and it "sends" a value for the temperature, just as it was a real temperature sensor attached to the heat pump.
> Is there a way to temporarily do this manually from HA or through MQTT Explorer for example?
> As it is now, the indoor temperature defaults to 20.5 degrees.

@Dauzzen , you can publish MQTT messages directly in HA, for example via an automation (the action MQTT: Publish is a way to go). I haven't used it myself (yet), but in theory this could work. There is also possible to publish MQTT commands in Node-Red if you're using that.

**Comment by DreamT80** [comment]
@ThermIQ Anders, are you making any progress in this? I don't want to stress you or anything ("no cow on the ice" as we say in Sweden ;) ), but it would be nice to know if you see a solution in the near future? Else I might upgrade anyway and set values via home built automations instead.

**Comment by ThermIQ** [comment]
I believe the services are still working:
thermiq_mqtt.write_id
thermiq_mqtt.write_reg
thermiq_mqtt.write_mode
thermiq_mqtt.set_indr_t
thermiq_mqtt.set_evu

You could give that a try. Then of course sending "raw" mqtt messages are possible with ha, nodeRed, MQTT-Explorer etc

**Comment by ThermIQ** [comment]
I'm halfway through a major restruct of the code to remove the need for manual entry into configuration.yaml and to alllow more than on heatpump. And of course, finding a way through for updating inputs and sending mqtt messages  that is now broken.

It won't happen this week but likely ready in November (Year is intentionally left out)

**Comment by DreamT80** [comment]
> I believe the services are still working: thermiq_mqtt.write_id thermiq_mqtt.write_reg thermiq_mqtt.write_mode thermiq_mqtt.set_indr_t thermiq_mqtt.set_evu
> 
> You could give that a try. Then of course sending "raw" mqtt messages are possible with ha, nodeRed, MQTT-Explorer etc

Great! Can you give examples on how to use the services? Couldn't find it in the documentation. For the moment i'd like to set the requested indoor temp (which i guess I use thermiq_mqtt.set_indr_t with a value of 1?), and I'd also want to set the hotter starting temperature (.thermiq_mqtt_hotwater_start_t).

**Comment by kheikola** [comment]
@DreamT80 sending messages with Node-RED extension at least works nicely. To test setting indoor target temperature (d50) to 20 C, you could create an inject node with msg.payload = {"d50":20}
And then have MQTT out node with your MQTT broker selected and with write topic: ThermIQ/ThermIQ-room2/write
![image](https://user-images.githubusercontent.com/114338725/203132006-f202e09b-279b-4c08-b5a8-3bd45549adc9.png)
Hotwater start temp would be d58, you can find the register list from the install guide: https://thermiq.net/ThermIQ_MQTT_Installation.pdf

@ThermIQ while restructing the code, may I propose to include also HA entity for 'rssi' (wifi signal strength)?

**Comment by DreamT80** [comment]
> @DreamT80 sending messages with Node-RED extension at least works nicely. To test setting indoor target temperature (d50) to 20 C, you could create an inject node with msg.payload = {"d50":20} And then have MQTT out node with your MQTT broker selected and with write topic: ThermIQ/ThermIQ-room2/write ![image](https://user-images.githubusercontent.com/114338725/203132006-f202e09b-279b-4c08-b5a8-3bd45549adc9.png) Hotwater start temp would be d58, you can find the register list from the install guide: https://thermiq.net/ThermIQ_MQTT_Installation.pdf
> 
> @ThermIQ while restructuring the code, may I propose to include also HA entity for 'rssi' (wifi signal strength)?

Thanks, @kheikola! I think I will use HA for sending messages, but the principle should the same when using MQTT.

It would however be nice to know how to use the thermiq_mqtt-service. The data should be the same (sending data to dXX), but I guess the payload should be formatted differently.

**Comment by ThermIQ** [comment]
Isn't there some info if you go to developer tools services and select it?

**Comment by DreamT80** [comment]
> Isn't there some info if you go to developer tools services and select it?

Yes, as soon as I understood how it worked.. :). Works fine. Thank you!

**Comment by DreamT80** [comment]
I have some trouble setting a dynamic value, i.e. from a HA entity. 

A static value works fine

```
service: thermiq_mqtt.write_id
data: {"register_id":"sensor.thermiq_mqtt_indoor_requested_t", "value":21.0}
```

But, I can't manage it to work with a dynamic value:

```
service: thermiq_mqtt.write_id
data: {"register_id":"sensor.thermiq_mqtt_indoor_requested_t", "value":{{ states('sensor.heat_capacitor_evaluated_heat') | float }} }
```

I get
`No MQTT message sent due to missing value:[21.0]`
in the log, hinting that the syntax probably isn't correct. But I don't know how to correct it..

**Comment by ThermIQ** [comment]
The brave can now try out the v2.0.0 release where this should be solved. Please note that the setup is now done through a graphical flow when adding the integration. Please remove all entries from configuration.yaml

**Comment by igalg99** [comment]
hmm I was brave :)
Updated, removed the entries in configuration.yaml.  restarted. added integration. double checked correct node-name. then restarted again.
the Lovelace is broken thought. do I need to reconfigure it too?

**Comment by ThermIQ** [comment]
First, check with HA Developer Tools to see if you have the input instances and there are values in them. If you have instancess but no values you are likely not having the correct mqtt node name. Mine is ThermIQ/ThermIQ-room2, note that there is no slash in the beginning nor end....

If not, do you have anything in the log to help?

Remove the integration, restart and add (and restart?) to update settings

**Comment by igalg99** [comment]
Yes I have the same  ThermIQ/ThermIQ-room2 . I have copied it from the configuration and double checked in mqtt explorer
checked in HA developer.  value unavailable
tried to remove - restart - add - restart. 
or maybe you meant to remove it completly from HACS ? I have only removed from the integration panel

**Comment by ThermIQ** [comment]
It's not needed to completely remove it.

Update to v2.0.2 and check the logs, there should be some info there to post here

**Comment by igalg99** [comment]
Ok, done it. this is what I found in the logs about ThermIQ. 3 different errors:

This error originated from a custom integration.

Logger: custom_components.thermiq_mqtt
Source: custom_components/thermiq_mqtt/__init__.py:52
Integration: ThermIQ MQTT Integration (documentation, issues)
First occurred: 23:15:29 (1 occurrences)
Last logged: 23:15:29

Set up ThermIQ-MQTT integration entry vp1




This error originated from a custom integration.

Logger: custom_components.thermiq_mqtt
Source: custom_components/thermiq_mqtt/__init__.py:38
Integration: ThermIQ MQTT Integration (documentation, issues)
First occurred: 23:15:29 (1 occurrences)
Last logged: 23:15:29

Set up ThermIQ-MQTT integration




This error originated from a custom integration.

Logger: custom_components.thermiq_mqtt.heatpump
Source: custom_components/thermiq_mqtt/heatpump/__init__.py:221
Integration: ThermIQ MQTT Integration (documentation, issues)
First occurred: 23:15:29 (1 occurrences)
Last logged: 23:15:29

thermiq_mqtt_vp1 mqtt_node: [ThermIQ/ThermIQ-room2]

**Comment by ThermIQ** [comment]
None of them are errors but but i wanted the message to come through.

Any sensorn, inputs etc in the developer tool?

**Comment by igalg99** [comment]
ok I check now. yes sensors appear in the HA developer. I see I have still the old entities helpers which are unavailable but new entities show values.
just not sure why the Lovelace card is broken?

**Comment by ThermIQ** [comment]
Make sure you have latest Lovelace.

You can clean out the old in settings/integration/devices

**Comment by igalg99** [comment]
I did copy the latest one. it must be that new since the sensor names now are "sensor.thermiq_mqtt2_vp1_" instead of the previous "sensor.thermiq_mqtt2"

**Comment by igalg99** [comment]
now I got this. made new dashboard put the code in raw configuration
![image](https://user-images.githubusercontent.com/86168630/203659191-420d7871-b9ae-4e08-bd5f-ba388ad6874c.png)

**Comment by ThermIQ** [comment]
What does the MQTT message look like when you try to change the value?

What is the option MQTT Debug Write set to?

MQTT Explorer is a great tool

**Comment by igalg99** [comment]
I have enabled debug in the integration setup

This is what it looks like in mqtt explorer after I change the value 

![image](https://user-images.githubusercontent.com/86168630/203867143-1e55cfb8-53e9-4b4e-a651-a5e835d0ba6a.png)

**Comment by ThermIQ** [comment]
Hint. Disable "MQTT Debug Write" if you want to actual write to the HP. As you can see the end-point whit Debug enable is not correct. Great for debug, not so great if you want the heatpump to take action.

**Comment by igalg99** [comment]
> Hint. Disable "MQTT Debug Write" if you want to actual write to the HP. As you can see the end-point with Debug enable is not correct. Great for debug, not so great if you want the heatpump to take action.

Thanks for the hint. didnt know that. I have done it though and restarted home assistant but it still not working :(

**Comment by igalg99** [comment]
Ok, so now on version 2.0.2 after I have removed, restarted , installed , restarted , have the debug disabled . it WORKS ! :) 
thank you very much! I hope others can confirm!

**Comment by ThermIQ** [comment]
Great, I've focused on getting basic functionality back, and less on config flow and documentation. As mentioned "For the brave" and now also lucky :-)

**Comment by ioT-enthusiast** [comment]
Thank You, Version 2.02 works fine for me!

**Comment by igalg99** [comment]
> I got it also working. Steps taken:
> 
> * Remove current integration in HACS and Lovelace YAML
> * Restart
> * Install 2.0.2 in HACS
> * Restart
> * Install integration under settings Devices & Services
> * Restart
> * Add new Lovelace Card
> 
> Now MQTT messages are being sent to the HeatPump.
> 
> Still to do is to clean out the old Entities (Sensors) just need to find out where :/


I have cleaned them out in the "helpers" section. nearly all entites are created by helpers. If you go to the helpers section you will see a huge list. sort them by name and remove all these that dont have "vp1" the the name.

**Comment by barvidss** [comment]
I'm now on 2.0.3 and the lovelace control works again!
However I'm now missing all the thermiq_mqtt services. Without those I'm not able to set my automations up again.

Is there any way to get theese back? I've tried reinstalling the Thermiq stuff but made no difference.

**Comment by ThermIQ** [comment]
Therese are no services (yet). But As this integration builds on vanilla input_number I  think you can use the default services of these

**Comment by mhumaloja** [comment]
Hi guys, I followed this thread and fixed occured problem by installing 2.0.3. Everything seems to be working now. I set the language to Finnish (fi) in the initial setup and some of the sensors aren't translated perfectly. I would like to fix sensor translations, could you just point me to right direction? How can I fix sensor "friendly name" and icon?

**Comment by ThermIQ** [comment]
I would happily accept changes to any translations or new languages. All translation tables are in heatpunp/thermiq_regs.py.

Either check out your own github version, update, and make a pull request or mail me an updated version to add.

**Comment by barvidss** [comment]
> Therese are no services (yet). But As this integration builds on vanilla input_number I think you can use the default services of these

Yep, this worked fine (thank you):

service: input_number.set_value
data: {"entity_id": "input_number.thermiq_mqtt_vp1_indoor_requested_t", "value":20}

**Comment by mhumaloja** [comment]
> I would happily accept changes to any translations or new languages. All translation tables are in heatpunp/thermiq_regs.py.
> 
> Either check out your own github version, update, and make a pull request or mail me an updated version to add.

Thanks for pointing me to the right direction. I will not open any new issues for this. I'll just create a branch and edit the file there. I will make a pull request as I have it done. Might take some time to go forward with this when I have time to do it. I'll use Thermia Heatpump manual to match the translations to the manual and Heatpump menu terminology. Also if manual or menus have unnatural Finnish impressions I'll fix them to be more natural. (teacher's occupational hazards :D )

**Comment by ThermIQ** [comment]
I would greatly appreciate that! I've had some finnish support doing it but I have no way to check. Neither are the swedish names 100%

The settings displayed in the lovelace "fold"-panels is based on the value of the field "panel" and in each panel the "panel_order". If you also find a more natural way of organizing the different settings in the lovelace "fold"-panels you can change these but it will not take effect directly but I will then regenerate the lovelace file accordingly.

**Comment by ThermIQ** [comment]
I will close this one now as I have received positive feedback from several brave testers, thank you! 

There are still things to fix but the general crash from HA 2022.11 is now considered resolved in v2.x
