### ISSUE TITLE
Thermiq doesn't start up after upgrade to 1.2.5

### ISSUE THREAD

**Issue by lightheaded** [ThermIQ/thermiq_mqtt-ha#21]
## Version of the custom_component
1.2.5

## Configuration

```yaml
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/thermiq_mqtt/__init__.py:132
Integration: thermiq_mqtt (documentation, issues)
First occurred: 18:16:25 (1 occurrences)
Last logged: 18:16:25

Error during setup of component thermiq_mqtt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/thermiq_mqtt/__init__.py", line 132, in async_setup
    lang=lang.lower()
AttributeError: 'NoneType' object has no attribute 'lower'


```

## Describe the bug
The integration fails to start.

**Comment by lightheaded** [comment]
Could probably be made a bit more bulletproof, as with the thermiq_dbg option, such as if it's unspecified then it wouldn't fail to start.

**Comment by ThermIQ** [comment]
Should be fixed with v1.2.6
